"""Change volume column to BigInteger

Revision ID: 56a0820116d2
Revises: 
Create Date: 2024-08-26 17:09:58.025418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56a0820116d2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_stock_splits_date', table_name='stock_splits')
    op.drop_index('ix_stock_splits_id', table_name='stock_splits')
    op.drop_table('stock_splits')
    op.drop_index('ix_dividends_date', table_name='dividends')
    op.drop_index('ix_dividends_id', table_name='dividends')
    op.drop_table('dividends')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dividends',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('dividend', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='dividends_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='dividends_pkey'),
    sa.UniqueConstraint('company_id', 'date', name='_dividend_company_date_uc')
    )
    op.create_index('ix_dividends_id', 'dividends', ['id'], unique=False)
    op.create_index('ix_dividends_date', 'dividends', ['date'], unique=False)
    op.create_table('stock_splits',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('split_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], name='stock_splits_company_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='stock_splits_pkey'),
    sa.UniqueConstraint('company_id', 'date', name='_stock_split_company_date_uc')
    )
    op.create_index('ix_stock_splits_id', 'stock_splits', ['id'], unique=False)
    op.create_index('ix_stock_splits_date', 'stock_splits', ['date'], unique=False)
    # ### end Alembic commands ###
