"""Initial migration

Revision ID: 6551a1d9ba37
Revises: 
Create Date: 2024-08-25 22:27:07.217483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6551a1d9ba37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'sector')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('sector', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
