"""empty message

Revision ID: f4c56e296684
Revises: 6551a1d9ba37
Create Date: 2024-08-25 22:49:03.525834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4c56e296684'
down_revision: Union[str, None] = '6551a1d9ba37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('current_price', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'current_price')
    # ### end Alembic commands ###
